---
title: "Aprendizaje No Supervisado"
lang: es
---

El aprendizaje no supervisado es una técnica de aprendizaje automático que busca encontrar patrones en los datos sin tener una respuesta previa. Estudiaremos dos de los algoritmos más populares de aprendizaje no supervisado: el clustering y la reducción de dimensionalidad. En cada uno introduciremos los algoritmos más básicos. Motivamos al estudiante a explorar por su cuenta más a fondo el aprendizaje no supervisado, que es una rama de investigación muy activa.

## Análisis de componentes principales (PCA)

El análisis de componentes principales (PCA) es una técnica de aprendizaje no supervisado utilizada para simplificar conjuntos de datos correlacionados de alta dimensión, reduciendo su dimensionalidad mientras se conserva la mayor cantidad posible de varianza. PCA identifica las direcciones (componentes principales) a lo largo de las cuales los datos varían más y proyecta los datos originales sobre estas direcciones.

### Definición de los Componentes Principales

La intuición es la siguiente: La matriz de covarianza contiene la varianza de cada variable y su correlación con otras variables. Es una matriz simétrica, es decir, $\boldsymbol{\Sigma}_{ij} = \boldsymbol{\Sigma}_{ji}$. Por lo tanto, siempre es posible diagonalizarla. Esto quiere decir que podemos encontrar autovectores y autovalores de la matriz de covarianza. Estos autovectores son ortogonales entre ellos, en otras palabras, si cambianos la lista de variables $\{x_1, ..., x_q\}$ por una lista de autovectores $\{\phi_1, ..., \phi_q\}$, la matriz de covarianza de estos será diagonal. Esto es equivalente a cambiar de variables en el espacio de parámetros para obtener nuevas variables no correlacionadas.

Los componentes principales se definen a través de los autovectores de la matriz de covarianza. En los datos esta es $\mathbf{X}^T\mathbf{X}$, donde la componente $X_{ij}$ como siempre se refiere a la medición $i$, variable $j$ (cada fila es una medición y cada columna es una variable).

El primer vector de componentes principales, $\boldsymbol{\phi}_1$, es el autovector de $\mathbf{X}^T\mathbf{X}$ asociado al mayor autovalor. Representa la dirección en el espacio de características a lo largo de la cual los datos varían más. Es decir, la dirección en la que hay más información.

Formalmente, el primer componente principal se expresa como: 

$$
Z_1 = \mathbf{X}\boldsymbol{\phi}_1
$$

donde $\boldsymbol{\phi}_1$ satisface:

$$
\mathbf{X}^T\mathbf{X}\boldsymbol{\phi}_1 = \lambda_1\boldsymbol{\phi}_1
$$

siendo $\lambda_1$ el mayor autovalor. Al ser un autovector, $\boldsymbol{\phi}_1$ está definido salvo una constante multiplicativa.

El siguiente componente principal $\boldsymbol{\phi}_2$ es el autovector asociado al siguiente autovalor más grande, y así sucesivamente. El autovalor de la matriz de covarianza representa la varianza de los datos en esa dirección. Escogemos los $m$ autovectores de mayor autovalor para que los componentes principales expliquen la mayor variabilidad posible de los datos.

Los autovectores de una matriz simétrica son ortogonales entre sí, es decir, $\boldsymbol{\phi}_i^T\boldsymbol{\phi}_j = 0$ para $i \neq j$. Por lo tanto, los componentes principales no están correlacionados entre sí.

En este sentido, el PCA con $m$ componentes busca las $m$ direcciones no correlacionadas que explican la mayor variabilidad posible de los datos.

### Proporción de Varianza Explicada (PVE)

La proporción de varianza explicada por cada componente principal está dada por:

$$
\text{PVE}_m = \frac{\sum_{i=1}^{n} z_{im}^2}{\sum_{j=1}^{p}\sum_{i=1}^{n} x_{ij}^2}
$$

La PVE ayuda a determinar cuántos componentes representan suficientemente los datos. Típicamente, se seleccionan componentes hasta que se observa un "codo" en el gráfico de scree.

### Consideraciones Prácticas

#### Escalado de las Variables

Generalmente, las variables requieren ser escaladas a varianza unitaria, especialmente si están medidas en distintas escalas, para asegurar que ninguna variable influya desproporcionadamente en el PCA.

#### Unicidad

Los componentes principales son únicos salvo un cambio de signo. Por lo tanto, los resultados de diferentes paquetes de software pueden diferir en los signos pero representarán las mismas direcciones en el espacio de características.

### Selección del Número de Componentes

Determinar el número de componentes principales es generalmente subjetivo. Prácticas comunes incluyen:

- Inspeccionar gráficos de scree para encontrar un "codo". Es decir, graficamos $\text{PVE}_i$ para $i=1,\dots,q$. La cantidad de varianza explicada subirá a medida que agregamos más componentes, pero llegará un punto donde ganaremos poco al agregar el siguiente. A esto se lo llama el "codo".
- Elegir suficientes componentes para capturar una proporción acumulada significativa de varianza. Por ejemplo, si queremos capturar el 95% de la varianza, usamos $\sum_{i=1}^{m} \text{PVE}_i \geq 0.95$.

En contextos supervisados, el número de componentes puede seleccionarse mediante validación cruzada.

### Usos Adicionales del PCA

Más allá de la visualización y la reducción de dimensionalidad, PCA puede utilizarse para:

- Preprocesamiento de datos para regresión o clasificación.
- Imputación de datos faltantes, es decir, completar valores faltantes en la matrix de datos $\mathbf{X}$.
- Mejorar la estabilidad y reducir el ruido en varios métodos analíticos.

### Ejemplo de PCA para compresión de imágenes

En este ejemplo, usamos PCA para comprimir una imagen de un dígito escrito a mano. Usamos los datos de dígitos del paquete `sklearn`.

```{python}
#| label: fig-digitos
#| fig-cap: "Dígitos de MNIST"
#| code-fold: true

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_openml

mnist = fetch_openml('mnist_784', as_frame=False)
X_train, y_train = mnist.data[:60_000], mnist.target[:60_000]
X_test, y_test = mnist.data[60_000:], mnist.target[60_000:]

indexes = np.random.random_integers(0, len(X_train), 9)
sample = X_train[indexes].reshape(3,3,28,28)
plt.imshow(np.block([[sample[i,j] for i in range(3)] for j in range(3)]), cmap='gray_r')
```

En scikit-learn, el PCA se puede aplicar con la clase `PCA` del módulo `decomposition`. Podemos especificar que el número de componentes principales explique una proporción de la varianza. Pediremos el 95% de la varianza.

```{python}
#| label: fig-pca-digitos
#| fig-cap: "PCA para compresión de imágenes"
#| code-fold: true

from sklearn.decomposition import PCA

pca = PCA(n_components=0.95)
X_reduced = pca.fit_transform(X_train)

X_recovered = pca.inverse_transform(X_reduced)
sample = X_recovered[indexes].reshape(3,3,28,28)
plt.imshow(np.block([[sample[i,j] for i in range(3)] for j in range(3)]), cmap='gray_r')
```

## Métodos de Clustering

### Introducción

El clustering es un conjunto amplio de técnicas para encontrar subgrupos (clusters) en un conjunto de datos. El objetivo es dividir las observaciones en grupos distintos de tal manera que las observaciones dentro de un mismo grupo sean similares entre sí y diferentes a las de otros grupos. La definición de similitud o diferencia depende del contexto y del tipo específico de datos.

Aunque tanto el clustering como PCA buscan simplificar datos, sus mecanismos son diferentes:

- **PCA** busca una representación de baja dimensión que explique gran parte de la varianza.
- **Clustering** busca subgrupos homogéneos entre las observaciones.

### Clustering K-means

El clustering K-means es un método sencillo para particionar un conjunto de datos en $K$ clusters distintos y no superpuestos. Es necesario especificar previamente el número $K$ de clusters.

Dado un conjunto de observaciones $ x_{ij} $, se busca minimizar la variación intra-cluster:

$$
\min_{C_1, \dots, C_K} \sum_{k=1}^{K} \frac{1}{|C_k|}\sum_{i,i' \in C_k}\sum_{j=1}^{p}(x_{ij}-x_{i'j})^2
$$

donde $C_k$ representa el conjunto de índices de las observaciones en el cluster $k$.

#### Algoritmo K-means

1. Asignar aleatoriamente cada observación a uno de los $K$ clusters.
2. Iterar hasta que las asignaciones no cambien:
   - Calcular el centroide de cada cluster (vector promedio).
   - Reasignar cada observación al cluster cuyo centroide esté más cerca (en términos de distancia euclidiana).

El resultado es una solución óptima local (puede no encontrar la solución óptima global), por lo que conviene repetir el algoritmo múltiples veces desde diferentes inicializaciones aleatorias.

El paso 1 es crucial para el resultado final. Si se elige mal, el algoritmo puede converger a un resultado subóptimo. Existen varias estrategias que mejoran la elección inicial. Por ejemplo, se puede elegir el centroide inicial como el punto más alejado de los centroides de los clusters ya existentes, que es lo que hace el algoritmo `KMeans++` implementado en `sklearn` por defecto cuando se usa el método `KMeans`.

### Elección de la medida de disimilitud

La distancia euclidiana es común, pero pueden preferirse otras medidas como la basada en correlación, que considera similares aquellas observaciones con perfiles correlacionados, independientemente de sus magnitudes absolutas.

### Cuestiones prácticas

- **Escalado**: Se recomienda escalar las variables a desviación estándar uno, especialmente cuando están medidas en escalas distintas. Esto es porque la distancia es sensible a la escala de las variables.
- **Robustez**: Los resultados del clustering pueden ser sensibles a decisiones como tipo de vínculo, escalado y selección del número de clusters. Por lo tanto, es recomendable evaluar la robustez del clustering mediante diferentes configuraciones y subconjuntos del conjunto de datos.

### Ejemplo de clustering K-means

```{python}
#| label: fig-clustering-kmeans-blobs
#| fig-cap: "Clustering K-means para datos ficticios"
#| code-fold: true

from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs

k = 5
X, y = make_blobs(n_samples=500, centers=k, n_features=2, random_state=42)
# make the blobs: y contains the cluster IDs, but we
# will not use them; that's what we want to predict

kmeans = KMeans(n_clusters=k, random_state=42)
y_pred = kmeans.fit_predict(X)

plt.scatter(X[y==0,0], X[y==0,1])
plt.scatter(X[y==1,0], X[y==1,1])
plt.scatter(X[y==2,0], X[y==2,1])
plt.scatter(X[y==3,0], X[y==3,1])
plt.scatter(X[y==4,0], X[y==4,1])

# Create a mesh grid for plotting the decision boundary
x_min, x_max = X[:, 0].min() - 0.5, X[:, 0].max() + 0.5
y_min, y_max = X[:, 1].min() - 0.5, X[:, 1].max() + 0.5
xx, yy = np.meshgrid(np.arange(x_min, x_max, 0.01),
                     np.arange(y_min, y_max, 0.01))

# Predict the class of each point on the mesh grid
Z = kmeans.predict(np.c_[xx.ravel(), yy.ravel()])
# Reshape Z to a 2D array
Z = Z.reshape(xx.shape)

# Create a colormap for plotting the decision boundary
#cmap = ListedColormap(['red', 'green', 'blue', 'yellow', 'gray'])

# Plot the decision boundary
plt.contourf(xx, yy, Z, cmap='jet', alpha=0.2)
```

En la figura @fig-clustering-kmeans-blobs se muestra el resultado del clustering K-means para datos ficticios. Vemos que funciona bien para este caso. 

### Ejemplo de clustering para segmentación de imágenes

Ahora queremos segmentar imágenes. Es decir, queremos agrupar píxeles similares entre sí. Esto ocurre frecuentemente en física, donde podemos tener imágenes de un experimento y nos gustaría identificar objetos o regiones. Nuestro ejemplo será reducir los colores de una imagen. Cada píxel tiene un color, que es un vector de tres componentes (rojo, verde, azul). Queremos agrupar píxeles similares entre sí en el espacio de colores.

```{python}
#| label: fig-ladybug
#| fig-cap: "Imagen de muestra que queremos segmentar"
#| code-fold: true

from PIL import Image
from pathlib import Path

IMAGES_PATH = Path('data')
filename = 'ladybug.png'
filepath = IMAGES_PATH / filename
image = np.asarray(Image.open(filepath))

plt.imshow(image)
```

En la figura @fig-ladybug se muestra una imagen de muestra que queremos segmentar.

```{python}
#| label: fig-ladybug-segmented-10
#| fig-cap: "Imagen segmentada en 10 clusters, coloreada con los centroides de los clusters"
#| code-fold: true

def cluster_image(n_clusters):
    X = image.reshape(-1, 3) # Convertir en tres matrices, una por color
    kmeans = KMeans(n_clusters=n_clusters, random_state=42).fit(X) # entrenar un clustering k-medias
    img_segmentada = kmeans.cluster_centers_[kmeans.labels_] # reemplazar cada píxel por su etiqueta de cluster
    img_segmentada = img_segmentada.reshape(image.shape).astype(int) # convertir de nuevo en una imagen

    plt.imshow(img_segmentada)

cluster_image(10)
```

En la figura @fig-ladybug-segmented-10 se muestra el resultado del clustering K-means para la imagen de la figura @fig-ladybug. Cada cluster se colorea con el color del centroide, es decir, con el color del punto central del cluster. Hagámoslo para menos clusters

```{python}
#| label: fig-ladybug-segmented-5
#| fig-cap: "Imagen segmentada en 5 clusters, coloreada con los centroides de los clusters"
#| code-fold: true
cluster_image(5)
```

En la figura @fig-ladybug-segmented-5 se muestra el resultado del clustering K-means para la imagen de la figura @fig-ladybug con 5 clusters.

## Ejercicios sugeridos

12.3, 12.6, 12.7

- Suponga que realizamos un PCA de un conjunto de datos y obtenemos que el primer componente principal explica el 95% de la varianza. ¿Qué significa esto?
