---
title: "Distribuciones de Probabilidad"
---

Hablamos de **variables aleatorias** como variables que pueden tomar un valor aleatorio dentro de un cierto conjunto. Cada valor prosible tiene una cierta probabilidad. Esto lo haremos más preciso en esta sección.

## Una variable aleatoria 

### Distribuciones de probabilidad 

Consideremos primero una variable discreta. Decimos que la variable $x$ tiene una probabilidad $P[x_k]$ de tomar el valor $x_k$. Este valor está dado por una **distribución de probabilidad**. Es decir una función $p$ tal que
$$
P[x_k] = p(x_k)\,.
$$
Esta cumple

- $p$ es univaluada y $p(x) \geq 0$.
- La probabilidad total es $1$, es decir $\sum_i p(x_i) = 1$.

Definimos también la **distribución cumulativa de probabilidad** 
$$
F(x) = \sum_{x_k \leq x} p(x_k)\,.
$$
Es decir, es la probabilidad de obtener un valor menor a $x$.

Para variables que toman valores continuos, la probabilidad de un valor dado tiende a cero (como hay infinitos valores, la probabilidad de cada uno debe ser minúscula para que su suma sea $1$). Por ese motivo no hablamos de una distribución de probabilidad sino de una **función de densidad de probabilidad** $\rho(x)$ tal que la probabilidad de obtener un resultado en el intervalo $[a,b]$ es
$$
P[a \leq x \leq b] = \int_a^bdx\,\rho(x)\,.
$$
Esta cumple

- $\rho$ es univaluada y $\rho(x) \geq 0$.
- La probabilidad total es $1$, es decir $\int_{-\infty}^\infty dx\,\rho(x) = 1$.

Análogamente definimos la distribución cumulativa de probabilidad
$$
F(x) = \int_{-\infty}^x dx'\,\rho(x')\,.
$$

### Valores esperados

Definimos el **valor esperado** de una variable discreta como
$$
\langle x\rangle \equiv \sum_x xp(x)\,.
$$
Para una variable continua
$$
\langle x\rangle \equiv \int_{-\infty}^\infty dx\,x\rho(x)\,.
$$

De esta manera los **momentos** son
$$
\mu'_m \equiv \langle x^m \rangle\,,
$$
y los **momentos centrales**
$$
\mu_m \equiv \left\langle (x - \langle x\rangle)^m\right\rangle\,.
$$

De la definición de valor esperado se puede demostrar para una constante $c$
$$
\langle cx\rangle = c\langle x\rangle\,,\quad \langle x_1 + x_2 + ... + x_n\rangle = \langle x_1\rangle + \langle x_2 \rangle + ... + \langle x_n\rangle\,.
$$
Además si las variables $x_1, ..., x_n$ son independientes
$$
\langle x_1 ... x_n\rangle = \langle x_1\rangle ...\langle x_n\rangle\,.
$$

## Varias variables 

### Distribución de probabilidad conjunta

Si tenemos varias variables aleatorias, las definiciones son muy análogas. Por ejemplo, la **distribución de probabilidad conjunta**
$$
P[a_1\leq x_1 \leq b_1, ..., a_n \leq x_n \leq b_n] \equiv \int_{a_n}^{b_n}...\int_{a_1}^{b_1}\prod_{i=1}^n dx_i\, \rho(x_1, ..., x_n)\,.
$$

### Distribución marginal y condicional

Si nos preguntamos cuál es el valor de una variable, independientemente del valor que tomen todas las demás, sólo tenemos que sumar sobre todos los valores de las demás variables. Esta se llama la **distribución marginal**
$$
\rho^M(x_1) = \int_{-\infty}^\infty...\int_{-\infty}^\infty \prod_{i=2}^n dx_i\,\rho(x_1, x_2, ..., x_n)\,.
$$
Análogamente, si queremos la probabilidad conjunta para algunas variables, marginalizamos sobre todas las demás 
$$
\rho^M(x_1, ..., x_m) = \int_{-\infty}^\infty...\int_{-\infty}^\infty \prod_{i=m+1}^n dx_i\,\rho(x_1, x_2, ..., x_n)\,.
$$}

Una pregunta distinta, es si *fijamos* el valor de las demás variables y nos preguntamos por la probabilidad de las restantes. Esta es la **distribución condicional**
$$
\rho^C(x_1, ..., x_m| x_{m+1}, ..., x_n) \equiv \frac{\rho(x_1, ..., x_n)}{\rho^M(x_{m+1}, ..., x_n)}\,.
$$

Esto nos permite escribir por ejemplo la siguiente relación
$$
\rho^C(x|y) = \frac{\rho^C(y|x)\rho^M(x)}{\rho^M(y)}\,,
$$
o también 
$$
\rho(x, y) = \rho^C(x|y)\rho^M(y)\,.
$$
Decimos que dos variables son **independientes** si
$$
f(x, y) = f^M(x)f^M(y)\,.
$$

### Momentos y valores esperados 

Se definen de forma análoga a una variable. Por ejemplo, definimos la covarianza como el segundo momento central 
$$
\text{cov}(x_i, x_j) \equiv \sigma_{ij} \equiv \int_{-\infty}^\infty...\int_{-\infty}^\infty \prod_{i=1}^n dx_i\, (x_i - \mu_i)(x_j - \mu_j) \rho(x_1, ..., x_n)\,.
$$
La condición $\sigma_{ij} = 0$ es necesaria (pero no suficiente) para que dos variables sean independientes.

## Funciones de una variable aleatoria 

Supongamos que la cantidad $y$ es una función de la variable aleatoria $x$. Podemos calcular su distribución de probabilidad haciendo un simple cambio de variable
$$
\rho(y) = \sum_{x}\rho(x)\left|\frac{dx}{dy}\right|\,.
$$
Donde la suma es sobre todos los puntos tal que $y = y(x)$.

Cuando hay varias variables, usamos el Jacobiano.

## Algunas distribuciones de probabilidad 

### Uniforme

Si la probabilidad es la misma en todas partes dentro de un intervalo
$$
\rho(x) \equiv u(x; a, b) = \begin{cases}
\frac{1}{b - a}\quad a\leq x \leq b\,
0\quad \text{de otra manera}
\end{cases}\,.
$$
Esta probabilidad es útil por ejemplo para generar números aleatorios. Cualquier variable se puede convertir en una variable con distribución uniforme mediante $u = F[x]$.

### Normal (Gaussiana)

Ubicua en física por motivos que discutiremos en unos minutos. La famosa distribución a campana
$$
\rho(x) \equiv n(x; \mu, \sigma) = \frac{1}{\sqrt{2\pi}\sigma}\exp\left[-\frac{(x - \mu)^2}{2\sigma^2}\right]\,.
$$

La utilidad de la gaussiana es que por motivos que vermos representa los errores de muchas cantidades medidas. Entonces es útil saber las probabilidades de obtener un resultado a un cierto número de desviaciones estándar de la media 

- $1\sigma$ es $68.3\%$.
- $2\sigma$ es $95.4\%$.
- $3\sigma$ es $99.7\%$.

Para varias variables es similar
$$
\rho(\mathbf{x}) = \frac{1}{(2\pi)^{n/2}|V|^{1/2}}\exp\left[-\frac{1}{2}(\mathbf{x} - \mathbf{\mu})^T V^{-1} (\mathbf{x} - \mathbf{\mu})\right]\,.
$$
La covarianza es fácil de calcular y es $\sigma_{ij} = V_{ij}$.

Integrando, se puede demostrar que la distribución marginal también es una gaussiana.

### Binomial

La distribución binomial es para una variable discreta. Representa intentar muchas veces un experimento con probabilidad de éxito $p$. Esta distribución es la probabilidad de obtener $r$ éxitos en $n$ intentos
$$
p(r; p, n) = \frac{n!}{r!(n - r)!}p^r (1 - p)^{n - r}\,.
$$
Esta es fácil de deducir, especialmente si hacemos un ejemplo. Supongamos que realizamos el expeeimento $4$ veces. La probabilidad de obtener éxito en los primeros tres intentos y fracaso en el último ($+++-$) es $p^3(1 - p)^1$. Pero tenemos otras tres maneras de obtener tres éxitos: $+-++$, $++-+$, $-+++$. Por lo tanto, la probabilidad de obtener $3$ éxitos es $4p^3(1 - p)$. En general, el factor combinatorial curnta de cuántas maneradas hay de obtener $r$ éxitos en $n$ intentos.

### Poisson

Es muy importante en física. Representa la probabilidad de obtener $r$ éxitos cuando $n$ tiende a ser un número grande y $p$ tiende a ser pequeño tal que $pn \equiv \lambda$ permanece constante
$$
\lim_{n\rightarrow \infty} \frac{1}{r!}\frac{n!}{(n-r)!}\left(\frac{\lambda}{n}\right)^r\left(1 - \frac{\lambda}{n}\right)^{n - r} = \lim_{n\rightarrow \infty}\frac{1}{r!}n^r\frac{\lambda^r}{n^r}\left(1 - \frac{\lambda}{n}\right)^n = \frac{1}{r!}\lambda^r e^{-\lambda}\,.
$$
Entonces definimos la **distribución de Poisson**
$$
p(r; \lambda) = \frac{1}{r!}\lambda^r e^{-\lambda}\,.
$$

## Ejercicios sugeridos para estudiar para la prueba

3.5, 3.6, 4.2, 4.7, 4.8

