---
title: "Aprendizaje Automático para Física"
description: "Curso para estudiantes de física: probabilidad desde cero, modelos lineales, clasificación, validación y redes neuronales (incluyendo convolucionales y transformadores)."
---

## Bienvenidos

Este curso está diseñado específicamente para estudiantes de física que desean comprender y aplicar técnicas de aprendizaje automático en su investigación. Nuestro enfoque se centra en construir una comprensión intuitiva y profunda de los fundamentos. No se asume una base sólida en estadística.

## Estructura del Curso

El curso se divide en tres partes principales:

- Unidad 1: Fundamentos de Probabilidad y Estadística
    - Nociones básicas: eventos, probabilidad, independencia (19 de marzo)
    - Distribuciones de probabilidad (23 de marzo)
	- Función generatriz, momentos, teorema central del límite. (26 de marzo)
    - Verosimilitud y estimación (31 de marzo)
    - Mínimos cuadrados e intervalos de confianza (7 de abril)
    - Testeo de hipótesis (8 de abril)
	- Introducción a la teoría de la información (14 de abril)

- Unidad 2: Aprendizaje Automático Clásico
    - Aprendizaje Automático y Regresión lineal. (15 de abril)
    - Clasificación: Regresión logística y métricas. (22 de abril)
    - Selección de modelos y regularización. (28 de abril)
    - Árboles de decisión, random forests y boosting. (29 de abril)
    - Máquinas de vectores de soporte. (5 de mayo)
    - Aprendizaje no supervisado: clustering y reducción de dimensionalidad (6 de mayo)

- Unidad 3: Redes Neuronales
    - El perceptrón multicapa (12 de mayo)
    - Entrenamiento: Descenso de gradiente y diferenciación automática (19 de mayo)
    - Evaluación de modelos y regularización de redes neuronales (20 de mayo)
    - Redes convolucionales (26 de mayo)
    - Redes Residuales (27 de mayo)
    - Transformadores y el mecanismo de atención (2 de junio)

## Objetivos del Curso

Al finalizar este curso, los estudiantes serán capaces de:

1. Comprender los fundamentos matemáticos detrás de los métodos de machine learning y su interpretación en problemas de datos
2. Identificar qué técnicas son apropiadas para diferentes problemas en física
3. Implementar y adaptar algoritmos de aprendizaje automático para aplicaciones específicas
4. Evaluar críticamente los resultados y limitaciones de diferentes métodos
5. Comprender los principios fundamentales de las redes neuronales y su aplicación en problemas físicos sin tratarlas como cajas negras

## Metodología

El curso combina teoría rigurosa con ejemplos prácticos de física. Cada tema incluye:

- Fundamentos matemáticos
- Implementación en Python
- Ejemplos y aplicaciones en física
- Ejercicios prácticos

## Requisitos

- Cálculo multivariable
- Álgebra lineal básica
- Programación básica en Python
- Física universitaria general

No se requiere una base sólida en estadística. Esta se enseña durante el curso.

Esperamos que este curso les proporcione las herramientas necesarias para aplicar el aprendizaje automático en sus investigaciones en física.

## Referencias

Estas notas son más que nada un resumen de los siguientes libros:

- "Statistics for Physical Sciences", B.R. Martin, Elsevier (2012). (Probabilidad y estadística)

- "Statistics: A Guide to the Use of Statistical Methods in the Physical Sciences", Barlow, Wiley (1989).

- "An Introduction to Statistical Learning", James, Witten, Hastie, Tibshirani, Taylor, Springer (2023). Disponible libremente en [este enlace](https://www.statlearning.com/) (Aprendizaje automático)

- "Understanding Deep Learning", J.D. Prince, MIT Press (2023). Disponible libremente en [este enlace](https://udlbook.github.io/udlbook/) (Redes neronales)

- "Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow", Géron, O'Reilly (2022).

## Evaluación

Al final de la primera unidad se realizará una prueba escrita.

Al final de la segunda unidad se presentará un proyecto sobre aprendizaje automático (ver los [proyectos](proyectos)).

Al final de la tercera unidad se presentará un proyecto sobre redes neuronales con alguna aplicación a la física.

Cada uno vale un tercio de la nota final.

### Fechas de evaluaciones

- Prueba primera unidad: 21 de Abril.
- Proyecto aprendizaje automático: 13 de Mayo.
- Proyecto redes neuronales: 3 de Junio.

## Ejercicios

Al final de cada clase hay ejercicios sugeridos. Los números se refieren al libro correspondiente en cada unidad. Por ejemplo, si se escribe 1.1 en una de las clases de la unidad de Probabilidad y Estadística, se refiere al ejercicio 1.1 del libro "Statistics for Physical Sciences".

## Otros libros

- "Deep Learning", I. Goodfellow, Y. Bengio, A. Courville, MIT Press (2016). 

- "Dive into Deep Learning", A. Chen, S. Bird, L. Catlett, Dive into Deep Learning (2021). Disponible libremente en [este sitio](https://d2l.ai/).

## Otros recursos

- [Stanford Statistical Learning with Python](https://youtu.be/LvySJGj-88U?si=XOb-BjjBMxpg-ovf)
- [Videos basados en "Understanding Deep Learning" por T. Elsayed](https://www.youtube.com/playlist?list=PLRdABJkXXytCz19PsZ1PCQBKoZGV069k3)
